# Generated by Django 5.2.1 on 2025-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('real_temp', models.FloatField()),
                ('max_feel', models.FloatField()),
                ('min_feel', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
